name: safe_zone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  dartz: ^0.10.1
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.3.0
  google_fonts: ^6.2.1
  toastification: ^3.0.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  flutter_hooks: ^0.21.2
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  flutter_datetime_picker_plus: ^2.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  geolocator: ^14.0.2
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.4.15
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/images/org/otara_foundation/
    - assets/images/users/
    - assets/images/services/
    - assets/images/threats/
